### ISSUE TITLE
Banner plugin check succeeds when run alone, but fails while running all tests. 

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107-test#6] opened 2018-07-20 03:47 UTC
I must have done something wrong. 
Not sure what is causing the failure of the 'prepare' statement in mySQL class, but only when all UnitTests are run.

**Comment by Deltik** [comment] 2018-07-20 09:48
The tests are not isolated from each other because only one instance of e107 is spawned for each test suite, so tests can be affected by actions done in previous tests.

This issue is caused by `e_db_mysql::$mySQLaccess` getting set to `NULL`.  How that is happening, I haven't figured out yet.

**Comment by Deltik** [comment] 2018-07-20 10:32
This is fixed in e107inc/e107#3296.

**Closed** 2018-07-20 11:03 UTC
Labels: submodule-bug

**Comment by CaMer0n** [comment] 2018-07-20 18:37
You're the best! Thank you! :1st_place_medal:  :+1:
